# 1: Student Scores Array

In [ ]:
# create lists
math_scores = [80, 56, 78, 90, 52]
science_scores = [45, 89, 64, 19, 38]
history_scores = [94, 80, 75, 68, 33]

In [ ]:
import pandas as pd

In [ ]:
# PART 1

# define array with for loop
student_labels = []
for i in range(1, 6):
  student_labels.append('student-' + str(i))

print (student_labels, '\n')

# create series of data

math_pd = pd.Series(math_scores, student_labels)

print ('math_pd:')
print (math_pd)
print ()

science_pd = pd.Series(science_scores, student_labels)

print ('science_pd:')
print (science_pd)
print ()

history_pd = pd.Series(history_scores, student_labels)

print ('history_pd:')
print (history_pd)

['student-1', 'student-2', 'student-3', 'student-4', 'student-5']

math_pd:
student-1    80
student-2    56
student-3    78
student-4    90
student-5    52
dtype: int64

science_pd:
student-1    45
student-2    89
student-3    64
student-4    19
student-5    38
dtype: int64

history_pd:
student-1    94
student-2    80
student-3    75
student-4    68
student-5    33
dtype: int64

In [ ]:
# PART 2

labels = ['math_scores', 'science_scores', 'history_scores']

# mean scores
mean_math = math_pd.mean()
mean_science = science_pd.mean()
mean_history = history_pd.mean()
mean_scores = [mean_math, mean_science, mean_history]

mean_scores_pd = pd.Series(mean_scores, labels)

print ('mean scores:')
print (mean_scores_pd, '\n')

# max scores
max_math = math_pd.max()
max_science = science_pd.max()
max_history = history_pd.max()
max_scores = [max_math, max_science, max_history]

max_scores_pd = pd.Series(max_scores, labels)

print ('max scores:')
print (max_scores_pd)

mean scores:
math_scores       71.2
science_scores    51.0
history_scores    70.0
dtype: float64

max scores:
math_scores       90
science_scores    89
history_scores    94
dtype: int64

In [ ]:
# PART 3

# use between method

# print math scores between 50 and 70, including both
math_index = math_pd.between(50, 70, inclusive = True)
print ('math scores between 50 and 70:')
print (math_pd[math_index], '\n')

# print science scores below 50, excluding
science_index = science_pd.between(0, 50, inclusive = False)
print ('science scores below 50:')
print (science_pd[science_index])

math scores between 50 and 70:
student-2    56
student-5    52
dtype: int64

science scores below 50:
student-1    45
student-4    19
student-5    38
dtype: int64

# 2: Create and Change Panda Series

In [ ]:
# PART 1
import pandas as pd
import random as random

In [29]:
# make pandas series s1

N = 10

list1 = []

for i in range(N):
  list1.append(random.randint(1, 10))

index1 = []

for n in range(N):
  index1.append(str(n))

# pass list to pd.Series

s1 = pd.Series(list1, index = index1)
print ('s1 series:')
print (s1)

s1 series:
0     5
1     5
2     7
3    10
4     6
5     5
6     6
7     2
8     8
9     4
dtype: int64

In [27]:
# make pandas series s2

N = 10

list2 = []

for i in range(N):
  list2.append(random.randint(5, 10))

index2 = []

for n in range(N):
  index2.append(str(n))

# pass list to pd.Series
s2 = pd.Series(list2, index = index2)
print ('s2 series:')
print (s2)

s2 series:
0     8
1    10
2     8
3     6
4     6
5    10
6     5
7     6
8     9
9     9
dtype: int64

In [30]:
# PART 2

# find all data that are the same in s1 and s2

same_data = []

for i in s1.values:
  if i in s2.values:
    if i not in same_data:
      same_data.append(i)

print (same_data)

[5, 10, 6, 8]

In [31]:
# PART 3

# take out data that are in both s1 and s2

for i in s1.values:
  if i in s2.values:
    s1 = s1[s1 != i]
    s2 = s2[s2 != i]

print ('s1:')
print (s1)
print ()
print ('s2:')
print (s2)

s1:
2    7
7    2
9    4
dtype: int64

s2:
8    9
9    9
dtype: int64